services:
  task-0:
    build:
      context: .
      dockerfile: docker/Dockerfile_task0
    depends_on:
      - mysql
    env_file: .env
    volumes:
      - ./src:/var/www/html:ro
    ports:
      - "8000:8000"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PSWD}
      MYSQL_DATABASE: tl_test
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PSWD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 5
    networks:
      - app-network


networks:
  app-network:
    driver: bridge